import { Project, Task } from '../types';

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Cement Plant Maintenance',
    description: 'Annual maintenance and upgrade of cement production line',
    startDate: '2025-01-10',
    endDate: '2025-02-15',
    category: 'Maintenance',
    priority: 'high',
  },
  {
    id: '2',
    name: 'Quality Control Implementation',
    description: 'Implementing new quality control measures for concrete production',
    startDate: '2025-02-01',
    endDate: '2025-03-30',
    category: 'Quality',
    priority: 'high',
  },
  {
    id: '3',
    name: 'Safety Protocol Update',
    description: 'Updating safety protocols and training for construction sites',
    startDate: '2025-01-15',
    endDate: '2025-02-28',
    category: 'Safety',
    priority: 'high',
  },
  {
    id: '4',
    name: 'Sustainable Construction Initiative',
    description: 'Implementing eco-friendly construction practices',
    startDate: '2025-02-15',
    endDate: '2025-04-15',
    category: 'Sustainability',
    priority: 'medium',
  },
  {
    id: '5',
    name: 'Equipment Modernization',
    description: 'Upgrading construction equipment for better efficiency',
    startDate: '2025-03-01',
    endDate: '2025-05-15',
    category: 'Infrastructure',
    priority: 'medium',
  }
];

export const mockTasks: Task[] = [
  {
    id: '101',
    projectId: '1',
    name: 'Equipment Inspection',
    description: 'Complete inspection of cement production equipment',
    assignee: 'John Smith',
    dueDate: '2025-01-20',
    status: 'completed',
    completedAt: '2025-01-18T10:00:00Z',
  },
  {
    id: '102',
    projectId: '1',
    name: 'Parts Replacement',
    description: 'Replace worn-out components in production line',
    assignee: 'Mike Johnson',
    dueDate: '2025-01-30',
    status: 'in-progress',
  },
  {
    id: '103',
    projectId: '1',
    name: 'System Testing',
    description: 'Test production line after maintenance',
    assignee: 'Sarah Wilson',
    dueDate: '2025-02-10',
    status: 'in-progress',
  },
  {
    id: '201',
    projectId: '2',
    name: 'Quality Metrics Definition',
    description: 'Define new quality control parameters',
    assignee: 'Emily Brown',
    dueDate: '2025-02-15',
    status: 'completed',
    completedAt: '2025-02-14T15:30:00Z',
  },
  {
    id: '202',
    projectId: '2',
    name: 'Testing Procedures Setup',
    description: 'Establish new testing procedures for concrete',
    assignee: 'David Clark',
    dueDate: '2025-03-01',
    status: 'in-progress',
  },
  {
    id: '203',
    projectId: '2',
    name: 'Staff Training',
    description: 'Train quality control team on new procedures',
    assignee: 'Lisa Anderson',
    dueDate: '2025-03-15',
    status: 'in-progress',
  },
  {
    id: '301',
    projectId: '3',
    name: 'Risk Assessment',
    description: 'Conduct comprehensive risk assessment',
    assignee: 'Robert Martinez',
    dueDate: '2025-01-25',
    status: 'completed',
    completedAt: '2025-01-24T11:45:00Z', 
  },
  {
    id: '302',
    projectId: '3',
    name: 'Protocol Documentation',
    description: 'Update safety protocol documentation',
    assignee: 'Jennifer Lee',
    dueDate: '2025-02-10',
    status: 'in-progress',
  },
  {
    id: '303',
    projectId: '3',
    name: 'Safety Training',
    description: 'Conduct safety training sessions',
    assignee: 'William Turner',
    dueDate: '2025-02-20',
    status: 'in-progress',
  },
  {
    id: '401',
    projectId: '4',
    name: 'Environmental Impact Study',
    description: 'Assess current environmental impact',
    assignee: 'Maria Garcia',
    dueDate: '2025-02-28',
    status: 'completed',
    completedAt: '2025-02-27T09:20:00Z',
  },
  {
    id: '402',
    projectId: '4',
    name: 'Green Materials Selection',
    description: 'Select eco-friendly construction materials',
    assignee: 'James Wilson',
    dueDate: '2025-03-15',
    status: 'in-progress',
  },
  {
    id: '403',
    projectId: '4',
    name: 'Waste Reduction Plan',
    description: 'Develop waste reduction strategies',
    assignee: 'Anna Thompson',
    dueDate: '2025-03-30',
    status: 'in-progress',
  },
  {
    id: '501',
    projectId: '5',
    name: 'Equipment Audit',
    description: 'Audit current equipment efficiency',
    assignee: 'Chris Davis',
    dueDate: '2025-03-10',
    status: 'completed',
    completedAt: '2025-03-09T14:00:00Z',
  },
  {
    id: '502',
    projectId: '5',
    name: 'New Equipment Installation',
    description: 'Install modern construction equipment',
    assignee: 'Kevin White',
    dueDate: '2025-04-15',
    status: 'in-progress',
  },
  {
    id: '503',
    projectId: '5',
    name: 'Operator Training',
    description: 'Train operators on new equipment',
    assignee: 'Patricia Brown',
    dueDate: '2025-04-30',
    status: 'in-progress',
  }
];